name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Spellcheck all files
      - uses: rojopolis/spellcheck-github-actions@0.45.0
        name: Spellcheck
        with:
          source_files: '**/*' # Match all files recursively
          task_name: All Files Spellcheck
          output_file: spellcheck-output.txt

      # Upload the spellcheck report as an artifact
      - uses: actions/upload-artifact@v3
        if: '!cancelled()' # Do not upload artifact if job was cancelled
        with:
          name: Spellcheck Output
          path: spellcheck-output.txt
