name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run check-spelling Action
      - name: Spell Check
        uses: check-spelling/check-spelling@main
        with:
          config: .github/actions/spelling