name: Spell Check

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - name: Checkout code
        uses: actions/checkout@v3

      #  Setting up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      #  Installing  cspell
      - name: Install cspell
        run: npm install -g cspell@6.30.1

      #  Verifying cspell installation
      - name: Verify cspell version
        run: cspell --version

      #  Running  cspell with ignore file in .gthub file 
      - name: Run cspell
        run: cspell "**/*" cspell "**/*" --config .github/workflows/spelling/cspell.txt
