name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install cspell
      - name: Install cspell
        run: npm install -g cspell

      # Step 4: Run cspell on all files
      - name: Run cspell
        run: cspell "**/*" --exclude "node_modules/**,dist/**"